language: node_js

node_js:
  - "12"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - ~/.cache

install: yarn install

script: yarn run e2e

branches:
  only:
    - master
