version: '3'

services:
  app:
    working_dir: /app
    image: node:12
    ports:
    - 3000:3000
    volumes:
    - .:/app
    command: "yarn start"
    user: "${UID}:${GID}"
    environment:
      - YARN_CACHE_FOLDER=/app/.cache/yarn
      - CYPRESS_CACHE_FOLDER=/app/.cache/cypress
